config/routes.rb
Rails.application.routes.draw do

  root 'hellos#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hellos_controller.rb
class HellosController < ApplicationController
  before_action :set_hello, only: [:show, :edit, :update, :destroy]

  # GET /hellos
  # GET /hellos.json
  def index

  end

  # GET /hellos/1
  # GET /hellos/1.json
  def show
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hello
      @hellos = Hellos.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hello_params
      params.fetch(:hello, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hellos_helper.rb
module HellosHelper
end

app/views/hellos/_form.html.erb
<%= form_for(@hello) do |f| %>
  <% if @hello.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hello.errors.count, "error") %> prohibited this hello from being saved:</h2>

      <ul>
      <% @hello.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hellos/edit.html.erb
<h1>Editing Hello</h1>

<%= render 'form' %>

<%= link_to 'Show', @hello %> |
<%= link_to 'Back', hellos_path %>

app/views/hellos/index.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8">
    <title>Мечтатель, путешественник, фотолюбитель</title>
  </head>
  <body>

    <div>
      <p>"Должен вам сказать, что мы вовсе не хотим завоёвывать никакой космос. Мы хотим расширить Землю до его границ. Мы не знаем, что делать с другими мирами. Нам не нужно других миров. Нам нужно зеркало. Мы бьёмся над контактом, и никогда не найдём его. Мы в глупом положении человека, рвущегося к цели, которую он боится, которая ему не нужна. Человеку нужен человек." А.Тарковский.</p>
      <img src="image.jpg" alt="[Фото]">
      <h1>Catherine I</h1>
      <h2>QA engineer</h2>
    </div>

    <div>
      <h3>Обо мне</h3>
      <ul>
        <li>Люблю котиков, вкусно поесть и поспать</li>
        <li>Много путешествую, занимаюсь спортом</li>
        <li>Люблю горы, своих друзей и свою работу</li>
      </ul>
    </div>

    <div>
      <h3>Что я умею</h3>
      <ul>
        <li>Готовить</li>
        <li>Колоть дрова</li>
        <li>Тестить железо</li>
        <li>Вышивать крестиком</li>
      </ul>
    </div>

    <div>
      <h3>Последние посещенные места</h3>
      <ul>
        <li>Трир</li>
        <li>Арлон</li>
        <li>Гент</li>
        <li>Оостенде</li>
        <li>Брюгге</li>
        <li>Люксембург</li>
        <li>Кёльн</li>
        <li>Нанси</li>
        <li>Цюрих</li>
        <li>Лозанна</li>
        <li>Париж</li>
        <li>Афины</li>
        <li>Сунио</li>
        <li>Эгина</li>
      </ul>
    </div>

  </body>
</html>

app/views/hellos/new.html.erb
<h1>New Hello</h1>

<%= render 'form' %>

<%= link_to 'Back', hellos_path %>

app/views/hellos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_hello_path(@hello) %> |
<%= link_to 'Back', hellos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demoapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>